#!/bin/bash

# this script is supposed to be called from Makefile of your project to generate .go file with version information

export LC_ALL="C"

binary="$1"
version="$2"
maintainer="$3"
auto_build_tag="$4"
build_command="$5"

v=$(autorevision -t sh 2>/dev/null)
eval "$v"

cat <<END_OF_VERSION_FILE
// generated by: `basename $0` `for i in "$@"; do echo -n \"$i\"" "; done`
// DO NOT EDIT!

package main

import (
)

func init() {
	VersionInfo = ResponseVersion{
		Binary:         "$binary",
		Version:        "$version",
		Maintainer:     "$maintainer",
		AutoBuildTag:   "$auto_build_tag",
		BuildDate:      "$(date -u)",
		BuildHost:      "$(hostname -f)",
		BuildGoVersion: "$(go version)",
		BuildCommand:   "$build_command",
	}
}
END_OF_VERSION_FILE
